### ISSUE TITLE
QEMU crashes  after launching a SNP-enabled guest with TAP 

### ISSUE THREAD

**Issue by cowbon** [AMDESE/qemu#4]
Hi there,
I'm getting `Bus Error` from QEMU on branch `snp-v3`. The following is the command I used to launch QEMU
`
qemu-system-x86_64 -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 -machine memory-encryption=sev0,vmport=off -enable-kvm -machine q35 -cpu EPYC-v4 -smp 4 -m 8G,maxmem=32G,slots=10 -global driver=cfi.pflash01,property=secure,value=on -drive file=$HOME/AMDSEV/snp-release-2022-07-15/usr/local/share/qemu/OVMF_CODE.fd,index=0,if=pflash,format=raw,readonly -drive file=$HOME/AMDSEV/snp-release-2022-07-15/usr/local/share/qemu/OVMF_VARS.fd,index=1,if=pflash,format=raw -drive file=$HOME/$hda,format=qcow2,index=0,media=disk -netdev tap,id=hostnet1,ifname=tap1,script=$HOME/qemu-ifup,downscript=no -device e1000,netdev=hostnet1,id=net1,addr=0x5,mac=52:54:00:6a:5e:61 -vnc 0.0.0.0:9 -serial telnet::4559,server,nowait -monitor stdio
`
Inside tap script `qemu-ifup`:
```sh
#!/bin/sh
set -x

switch=virbr0

if [ -n "$1" ];then
        #tunctl -u `whoami` -t $1
        ip tuntap add $1 mode tap user `whoami`
        ip link set $1 up
        sleep 0.5s
        #brctl addif $switch $1
        ip link set $1 master $switch
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
```
There's no such issue with `sev-guest`. For `sev-snp-guest`, if I change the network type to `user`, then QEMU is working properly. How can I fix this?

**Comment by tlendacky** [comment]
Try adding romfile= to your network device, e.g.:
  -device e1000,netdev=hostnet1,id=net1,addr=0x5,mac=52:54:00:6a:5e:61,romfile=
