### ISSUE TITLE
ReducedPhysBits value

### ISSUE THREAD

**Issue by jpecholt** [AMDESE/qemu#7]
Hi there,
there is an ongoing discussion in the Kata Containers project [PR #5007](https://github.com/kata-containers/kata-containers/pull/5007)  about the value of the field `reduced-phys-bits` for SEV-SNP VMs passed to QEMU via the command line. 

We established that host and guest reduced physical address bits are to be treated separately, the host's address space is generally reduced by `5` on Epyc Milan platforms, while the guest's address space is always reduced by `1` for now (see [Manual Vol. 2](https://www.amd.com/system/files/TechDocs/24593.pdf), section 15.34.6).

In the QEMU `snp-v3`  code, this value is at times hardcoded, like [here](https://github.com/AMDESE/qemu/blob/snp-v3/target/i386/sev.c#L870):
```bash
SevCapability *
sev_get_capabilities(Error **errp)
{
...
    /*
     * When SEV feature is enabled, we loose one bit in guest physical
     * addressing.
     */
    cap->reduced_phys_bits = 1;

```
but can also be provided through the command line by adding `reduced-phys-bits=...` to the `sev-snp-guest` object, which is the value used when initializing the VM.

The documentation, however, states the [following](https://github.com/AMDESE/qemu/blob/snp-v3/qemu-options.hx#L5185):
>        When memory encryption is enabled, we loose certain bits in
>        physical address space. The ``reduced-phys-bits`` is used to
>        provide the number of bits we loose in physical address space.
>        Similar to C-bit, the value is Host family dependent. On EPYC,
>        the value should be 5.

Furthermore, I noticed the following behaviour.

SEV-VMs allow a range from `reduced-phys-bits=1-(2^32-1)`
SNP-VMs allow a range from `reduced-phys-bits=1-319`

Inside the guest, the value is always the same as the specified value up until `63`, after that it stays cropped at `63`, probably because of some bit mask for the 6-bit field somewhere. I concluded that value is not used inside the guest for now since it has no apparent impact. The field is set in the current [QEMU code](https://github.com/AMDESE/qemu/blob/snp-v3/target/i386/cpu.c#L5981) as follows:

```bash
    case 0x8000001F:
        *eax = sev_enabled() ? 0x2 : 0;
        *eax |= sev_es_enabled() ? 0x8 : 0;
        *eax |= sev_snp_enabled() ? 0x10 : 0;
        *ebx = sev_get_cbit_position();
        *ebx |= sev_get_reduced_phys_bits() << 6;
        *ecx = 0;
        *edx = 0;
        break;
```

This is the CPUID definition in [AMD's manual Vol. 3, section E.4.17](https://www.amd.com/system/files/TechDocs/24594.pdf) :

> ####  CPUID Fn8000_001F_EBX Secure Encryption
> |Bits |Field Name Description                            |
> |-----|--------------------------------------------------|
> |31:16| — Reserved.                                      |
> |15:12| NumVMPL Number of VM Permission Levels supported |
> |11:6 | PhysAddrReduction Physical Address bit reduction |
> |5:0  | CbitPosition C-bit location in page table        |

To me, it looks like the SNP-specific QEMU version should probably be updated to 
1) contain up-to-date information on the `reduced-phys-bits` field and its impact 
2) would benefit from not using both hard-coded values and user-specified values or at least explicitly state why this is done in each case (if the value is always `1` for now, is an extra field for the command line even necessary or can it be omitted until that changes?)
3) have some sort of (unified) verification of the input value since right now I can start an SEV-VM with `reduced-phys-bits=4294967295` but "only" boot SNP-VMS with up to `reduced-phys-bits=319`, (which might have to do with 4.) and 
4) probably use a bit mask when setting the `ebx` field for the reduced bits in the above CPU code since right now this overwrites all higher fields if I am not mistaken which could cause issues if these fields are used

I don't know if this is the best place to start this conversation or if there are mailing lists more suited for this, let me know if there is a better way. I am happy to hear your thoughts or be corrected in case I got anything wrong.

**Comment by tlendacky** [comment]
> Hi there, there is an ongoing discussion in the Kata Containers project [PR #5007](https://github.com/kata-containers/kata-containers/pull/5007) about the value of the field `reduced-phys-bits` for SEV-SNP VMs passed to QEMU via the command line.

Yes, I was added to that discussion recently and plan to submit patches to Qemu around the concerns raised from it.

> 
> We established that host and guest reduced physical address bits are to be treated separately, the host's address space is generally reduced by `5` on Epyc Milan platforms, while the guest's address space is always reduced by `1` for now (see [Manual Vol. 2](https://www.amd.com/system/files/TechDocs/24593.pdf), section 15.34.6).
> 
> In the QEMU `snp-v3` code, this value is at times hardcoded, like [here](https://github.com/AMDESE/qemu/blob/snp-v3/target/i386/sev.c#L870):

This has been present in the upstream version of Qemu since the original SEV support, so nothing specific to SNP.

> 
> ```shell
> SevCapability *
> sev_get_capabilities(Error **errp)
> {
> ...
>     /*
>      * When SEV feature is enabled, we loose one bit in guest physical
>      * addressing.
>      */
>     cap->reduced_phys_bits = 1;
> ```
> 
> but can also be provided through the command line by adding `reduced-phys-bits=...` to the `sev-snp-guest` object, which is the value used when initializing the VM.
> 
> The documentation, however, states the [following](https://github.com/AMDESE/qemu/blob/snp-v3/qemu-options.hx#L5185):
> 
> > ```
> >    When memory encryption is enabled, we loose certain bits in
> >    physical address space. The ``reduced-phys-bits`` is used to
> >    provide the number of bits we loose in physical address space.
> >    Similar to C-bit, the value is Host family dependent. On EPYC,
> >    the value should be 5.

Yes, this is incorrect and should be fixed. I'm planning on saying something along the lines of:

On EPYC, a guest will lose a maximum of 1 bit, so the value should be 1.

> > ```
> 
> Furthermore, I noticed the following behaviour.
> 
> SEV-VMs allow a range from `reduced-phys-bits=1-(2^32-1)` SNP-VMs allow a range from `reduced-phys-bits=1-319`
> 
> Inside the guest, the value is always the same as the specified value up until `63`, after that it stays cropped at `63`, probably because of some bit mask for the 6-bit field somewhere. I concluded that value is not used inside the guest for now since it has no apparent impact. The field is set in the current [QEMU code](https://github.com/AMDESE/qemu/blob/snp-v3/target/i386/cpu.c#L5981) as follows:
> 
> ```shell
>     case 0x8000001F:
>         *eax = sev_enabled() ? 0x2 : 0;
>         *eax |= sev_es_enabled() ? 0x8 : 0;
>         *eax |= sev_snp_enabled() ? 0x10 : 0;
>         *ebx = sev_get_cbit_position();
>         *ebx |= sev_get_reduced_phys_bits() << 6;
>         *ecx = 0;
>         *edx = 0;
>         break;

I plan on adding some value limitations here, e.g.:

```
*ebx = sev_get_cbit_position() & 0x3f; /* EBX[5:0] */
*ebx |= (sev_get_reduced_phys_bits() & 0x3f) << 6; /* EBX[11:6] */
```

Although, see below. If the values are validated against the possible range, then this can't overflow into other fields... not sure what would be best here, but the above changes would be very clear to the reader.

> ```
> 
> This is the CPUID definition in [AMD's manual Vol. 3, section E.4.17](https://www.amd.com/system/files/TechDocs/24594.pdf) :
> 
> > #### CPUID Fn8000_001F_EBX Secure Encryption
> > 
> > 
> > 
> > Bits
> > Field Name Description
> > 
> > 
> > 
> > 
> > 31:16
> > — Reserved.
> > 
> > 
> > 15:12
> > NumVMPL Number of VM Permission Levels supported
> > 
> > 
> > 11:6
> > PhysAddrReduction Physical Address bit reduction
> > 
> > 
> > 5:0
> > CbitPosition C-bit location in page table
> 
> To me, it looks like the SNP-specific QEMU version should probably be updated to
> 
> 1. contain up-to-date information on the `reduced-phys-bits` field and its impact
> 2. would benefit from not using both hard-coded values and user-specified values or at least explicitly state why this is done in each case (if the value is always `1` for now, is an extra field for the command line even necessary or can it be omitted until that changes?)

I believe that was a requirement during the initial review of the original SEV support and is meant to be used for determining compatibility of live migration.

> 3. have some sort of (unified) verification of the input value since right now I can start an SEV-VM with `reduced-phys-bits=4294967295` but "only" boot SNP-VMS with up to `reduced-phys-bits=319`, (which might have to do with 4.) and

I'll update the current check (which just checks for < 1) to check the range of 1 to 63 (11:6 -> 6 bits). For backwards compatibility I'm not sure we can require a value of 1, though.

> 4. probably use a bit mask when setting the `ebx` field for the reduced bits in the above CPU code since right now this overwrites all higher fields if I am not mistaken which could cause issues if these fields are used

With the range validation, that might not be necessary any more. It would be clearer and cleaner to do that, though.

> 
> I don't know if this is the best place to start this conversation or if there are mailing lists more suited for this, let me know if there is a better way. I am happy to hear your thoughts or be corrected in case I got anything wrong.

This works, I'll get a patch submitted to Qemu.

**Comment by jpecholt** [comment]
Hi, thanks for getting back to me so quickly! I personally am of the mindset that it's better to have too many check than too few, especially in C. So the bit mask for `ebx` will probably help legibility of that specific code area and the input check beforehand will help the user understand what valid inputs are since the bit mask alone would not raise an error. Then again, I'm not writing the patch so I am leaving this up to you.
Thanks again for addressing this issue. Shall we close it once your proposed patch will be merged?

**Comment by tlendacky** [comment]
Patches submitted: https://lore.kernel.org/qemu-devel/cover.1664550870.git.thomas.lendacky@amd.com/
