### ISSUE TITLE
undefined reference to `kvm_has_restricted_memory'

### ISSUE THREAD

**Issue by cowbon** [AMDESE/qemu#8]
Hi there,

I'm trying to build `snp-latest` branch and is getting the following error
```
FAILED: qemu-system-aarch64 
c++ -m64 -mcx16 @qemu-system-aarch64.rsp
/usr/bin/ld: libqemu-aarch64-softmmu.fa.p/softmmu_memory.c.o: in function `memory_region_init_ram':
/root/qemu/build/../softmmu/memory.c:3619: undefined reference to `kvm_has_restricted_memory'
/usr/bin/ld: libqemu-aarch64-softmmu.fa.p/softmmu_memory.c.o: in function `memory_region_init_rom_device':
/root/qemu/build/../softmmu/memory.c:3702: undefined reference to `kvm_has_restricted_memory'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [Makefile:165: run-ninja] Error 1
```
I'm using a system similar to CentOS 9, GCC version is `11.3.1`, is there any dependency I should install, or any compiler flag I need to set?

**Comment by mdroth** [comment]
Thanks for the bug report. Our build scripts currently build QEMU with the --target-list=x86_64-softmmu option, which should avoid this issue, but I've just pushed a fix to the snp-latest QEMU branch which should resolve the build error you're seeing if you want to retry with your original build options.
